os: linux

language: go

go:
  - 1.14.x

services:
  - docker

script:
  - go test -v ./...
  - CGO_ENABLED=0 go build -o demo

  - docker build -f Dockerfile -t dkroeg/demo:latest ./
  - GIT_SHA="$(git rev-parse --short HEAD)"
  - docker tag dkroeg/demo:latest dkroeg/demo:$GIT_SHA
  - echo "$REGISTRY_PASSWORD" || docker login --username $REGISTRY_USER --password-stdin
  - docker push dkroeg/demo:latest
  - docker push dkroeg/demo:$GIT_SHA
